apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: ks-stg
  name: kalp-studio-doc-stg-deployment
  labels:
    app: kalp-studio-doc-stg
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kalp-studio-doc-stg
  template:
    metadata:
      labels:
        app: kalp-studio-doc-stg
    spec:
      hostname: kalp-studio-doc-stg
      nodeSelector:
        noderole:	ks-nonprod-node-x 
      containers:
        - name: kalp-studio-doc-stg
          image: 025066284787.dkr.ecr.ap-south-1.amazonaws.com/kalp-studio-doc-stg:<VERSION>
          imagePullPolicy: IfNotPresent
          resources:
            requests:
              memory: '800Mi'
              cpu: '200m'
            limits:
              memory: '800Mi'
              cpu: '200m'
          readinessProbe:
              httpGet:
                path: /health
                port: 8000
              initialDelaySeconds: 120
              timeoutSeconds: 10
          livenessProbe:
              httpGet:
                path: /health
                port: 8000
              initialDelaySeconds: 120
              periodSeconds: 5
              timeoutSeconds: 10
              failureThreshold: 4
          ports:
            - name: http
              containerPort: 8000
              protocol: TCP
          # env:
          #   - name: LOG_LEVEL
          #     valueFrom:
          #       secretKeyRef:
          #         key: LOG_LEVEL
          #         name: stg-kalp-studio-doc 
---
apiVersion: v1
kind: Service
metadata:
  namespace: ks-stg
  name: kalp-studio-doc-stg-svc
  labels:
    svc: kalp-studio-doc-stg
spec:
  type: ClusterIP
  ports:
    - name: http
      port: 80
      targetPort: 8000
  selector:
    app: kalp-studio-doc-stg
