site_name: Kalp Studio Documentation
site_description: Kalp Studio's documentation provides developers with essential tools and resources to build, manage, and scale blockchain networks efficiently.
site_author: Siddhesh Patankar
copyright: Copyright © 2025 Kalp studio. All rights reserved.
repo_url: https://github.com/p2eengineering/kalp-studio-documentation
site_url: https://docs.kalp.studio/
repo_name: Kalp-studio-documentation

theme:
  extra_css:
    - stylesheets/extra.css
  font:
    text: Source Sans 3, sans-serif
  name: material
  logo: images/PNG.png 
    #- link: Introduction/welcome.md
  favicon: images/PNG.png
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.code.select
    # - content.footnote.tooltips
    # - content.tabs.link
    - content.tooltips
    # - header.autohide
    # - header.bold
    # - navigation.expand
    - navigation.footer
    - navigation.indexes
    # - navigation.instant
    # - navigation.instant.prefetch
    - navigation.instant
    - navigation.instant.progress
    # - navigation.prune
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.leftside
    - navigation.tracking
    - navigation.instant.progress
    - navigation.top
    - navigation.tabs
    - search.highlight
    - search.share
    - search.suggest
    - toc.follow  
  palette:
    # Palette toggle for automatic mode
    - media: "(prefers-color-scheme)"
      primary: white
      scheme: default
      toggle:
        icon: material/brightness-auto
        name: Switch to light mode

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      primary: white
      scheme: default
      accent: deep orange
      toggle:
        icon: material/eye
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      primary: black
      scheme: slate
      accent: deep orange
      toggle:
        icon: material/eye-outline
        name: Switch to system preference
  plugins:
  - multirepo:
      cleanup: true
      keep_docs_dir: false
  - search
  - open-in-new-tab
  - git authors
  icon:
    admonition:
      note: fontawesome/solid/note-sticky
      abstract: fontawesome/solid/book
      info: fontawesome/solid/circle-info
      tip: fontawesome/solid/bullhorn
      success: fontawesome/solid/check
      question: fontawesome/solid/circle-question
      warning: fontawesome/solid/triangle-exclamation
      failure: fontawesome/solid/bomb
      danger: fontawesome/solid/skull
      bug: fontawesome/solid/robot
      example: fontawesome/solid/flask
      quote: fontawesome/solid/quote-left

#  markdown_extensions:
#  - pymdownx.highlight:
#      anchor_linenums: true
#      line_spans: __span
#      pygments_lang_class: true
#  - pymdownx.inlinehilite
#  - pymdownx.snippets
#  - pymdownx.superfences
#  - pymdownx.highlight
#  - pymdownx.inlinehilite
#  - pymdownx.keys

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - admonition
  - pymdownx.arithmatex:
      generic: true
  - footnotes
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.mark
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html

nav:
  - Home: index.md

  - Kalp Studio:
    - Kalp Studio Overview:
      - What is Kalp Studio: 'Introduction/Kalp-studio-overview.md'
      - What is Kalp DLT: 'Introduction/Kalp-DLT.md'
    - Getting Started: 
        - How to Sign Up to Kalp Studio Platform: 'Products/Kalp-Studio-Console/Onboarding/How-to-Sign-Up-to-Kalp-Studio-Platform.md'
        - How to Log In to your Kalp Studio Account: 'Products/Kalp-Studio-Console/Onboarding/How-to-log-in-to-your-Kalp-Studio-Account.md'
        - How to Change your Kalp Studio Password: 'Products/Kalp-Studio-Console/Onboarding/How-to-Change-Kalp-Studio-Password.md'
        - How to Navigate Kalp Studio Platform as an Active User: 'Products/Kalp-Studio-Console/Dashboard/How-to-Navigate-Kalp-Studio-Dashboard-as-an-Existing-User.md'
        - How to Navigate Kalp Studio Dashboard as an New User: 'Products/Kalp-Studio-Console/Dashboard/How-to-Navigate-Kalp-Studio-Platform-as-an-New-User.md'
  
    - Kalp Studio Console: 
      - Products: 
      - Billing:
        - How does a new user access billing: 'Products/Kalp-Studio-Console/Billing/How-does-a-new-user-access-billing.md'
        - How does a subscribed user access billing: 'Products/Kalp-Studio-Console/Billing/How-does-a-subscribed-user-access-billing.md'
        - How does billing work on Kalp Studio Platform: 'Products/Kalp-Studio-Console/Billing/How-does-Billing-work-on-the-Kalp-Studio-Platform.md'
      - Credits:
        - How to add credit: 'Products/Kalp-Studio-Console/Credits/How-to-Add-Credit.md'
        - Navigate to the credit section: 'Products/Kalp-Studio-Console/Credits/Navigate-to-the-Credit-Section.md'
      - Faucets:
        - How to Get TestNest Gini Tokens Using Kalp Studio Faucet: 'Products/Kalp-Studio-Console/Faucets/How-to-Get-TestNet-Gini-Tokens-Using-Kalp-Studio-Faucet.md'
        - Kalp Wallet:
            - What is Kalp Wallet?: 'Introduction/Kalp-wallet.md'
            - How to navigate to kalp wallet: 'Products/Kalp Wallet/How-to-navigate-to-kalp-wallet-dashboard.md'
            - How to generate API auth key: 'Products/Kalp Wallet/How-to-generate-API-auth-key.md'
            - How to use connect widget feature: 'Products/Kalp Wallet/How-to-use-connect-widget-feature.md'
            - How to create a wallet: 'Products/Kalp Wallet/How-to-create-a-wallet.md'
            - How can I monitor all my transactions: 'Products/Kalp Wallet/How-can-I-monitor-all-my-transactions.md'
            - How to use embedded wallet configuration: 'Products/Kalp Wallet/How-to-Use-Embedded-Wallet-Configuration.md'
        - Kalp-Studio-Storage:
            - How to get started with kalp storage: 'Products/Kalp-Studio-Storage/How-to-get-started-with-kalp-studio-storage.md'
            - FAQ: 'Products/Kalp-Studio-Storage/FAQ.md'
            - IPFS OpenAPI Documentation: 'Products/Kalp-Studio-Storage/IPFS-OpenAPI-Documentation.md'
        - Kalp Instant Deployer:
            - What is Kalp Instant Deployer?: 'Introduction/Kalp-instant-deployer.md'
            - How to Deploy a Smart Contract on Kalp Studio: 'Products/Kalp-Studio-Console/Kalp-Instant-Deployer/How-to-Deploy-a-Smart-Contract-on-Kalp-Studio.md'
        - NFT Creator:
            - How to connect wallet: 'Products/NFT Creator/How to connect wallet.md'
            - How to create a catalog: 'Products/NFT Creator/How to create a catalog.md'
            - How to create NFT: 'Products/NFT Creator/How to create NFT.md'
            - How to delete NFT: 'Products/NFT Creator/How to Delete an NFT.md'
            - How to see all asset details: 'Products/NFT Creator/How to see all asset details.md'
            - How to view all your NFTs: 'Products/NFT Creator/How to view all your NFTs (Grid and List views).md'
            - How to view your catalog: 'Products/NFT Creator/How to view your Catalog.md'
        - KS-Query:
            - How to get started with KS Query: 'Products/KS-Query/How-to-get-started-with-KS-Query.md'
            - How to select blockchain and network on KS Query: 'Products/KS-Query/How-to-select-blockchain-and-network-on-KS-Query.md'
            - How to create an API Auth Key: 'Products/KS-Query/How-to-create-an-API-Auth-Key.md'
            - How to view all your API's: 'Products/KS-Query/How-to-view-your-all-APIs.md'
            - How to view your Dashboard & Subscription details: 'Products/KS-Query/How-to-view-your-Dashboard-and-subscription-details.md'
            - How to build explorer using KS Query: 'Products/KS-Query/How-to-built-explorer-using-ks-query.md'
            - How to invoke API of KS Query: 'Products/KS-Query/How-to-invoke-api-of-KS-query.md'
        - API Gateway:
            - How to generate API endpoints: 'Products/Kalp-Studio-Console/API-Gateway/How-to-generate-API-endpoints.md'
            - How to navigate to the list of smart contract: 'Products/Kalp-Studio-Console/API-Gateway/How-to-Navigate-to-the-List-of-Smart-Contract.md'
        - Token-Studio:
            - How to get started with token creator: 'Products/Token-Studio/How-to-get-started-with-token-studio.md'
            - How to connect wallet: 'Products/Token-Studio/How-to-connect-wallet.md'
            - How to create token: 'Products/Token-Studio/How-to-create-token.md'
            - How to view list of token created: 'Products/Token-Studio/How-to-view-list-of-token-created.md'
            - How to view subscription details: 'Products/Token-Studio/How-to-view-subscription-details.md'
            - How to create token with Kalp DLT: 'Products/Token-Studio/How-to-create-token-with-kalp-dlt.md'
    - KS Pay:
            - How to Add credentials and get them verified on KS Pay: 'Products/KS-Pay/How-to-Add-Credentials-and-Get-Them-Verified-on-KS-Pay.md'
            - How to change the password on KS Pay: 'Products/KS-Pay/How-to-change-the-password-on-KS-Pay.md'
            - How to configure webhook on KS Pay: 'Products/KS-Pay/How-to-Configure-Webhook-on-KS-Pay.md'
            - How to integrate NPM on KS Pay: 'Products/KS-Pay/How-to-Integrate-NPM-on-KS-Pay.md'
            - How to manage payment gateway: 'Products/KS-Pay/How-to-manage-Payment-Gateway.md'
            - How to Access your profile on KS Pay: 'Products/KS-Pay/How-to-access-your-profile-on-KS-Pay.md'
            - How to view your transactions: 'Products/KS-Pay/How-to-view-your-transactions.md'
            - How to register your app on KS Pay: 'Products/KS-Pay/How-to-register-your-app-on-KS-Pay.md'
            - How to add a company on KS Pay: 'Products/KS-Pay/How-to-add-a-company-on-KS-Pay.md'
            - How to generate API Key on KS Pay: 'Products/KS-Pay/How-to-generate-API-Key.md'
            - How to add a domain on KS Pay: 'Products/KS-Pay/How-to-add-a-domain.md'
    - Referral Program:
            - Kalp Studio Referral Program: 'Products/Referral-Program/User Guide - For Kalp Studio Referral Program.md'
            - Kalp Studio Scholarship Referral: 'Products/Referral-Program/User Guide - For Kalp Scholarship Referral.md'    
        
  - Dev Documentation:
      - Kalp DLT:
          - Use the kalp SDK:
              - Kalp Golang SDK: 'Dev-documentation/Kalp-DLT/Use-the-kalp-sdk/Kalp-golang-sdk.md'
          - KRC Token Standard:
              - KRC 20 Token Contract: 'Dev-documentation/Kalp-DLT/KRC-Token-Standard/KRC-20-Token-Contract.md'
              - KRC 721 Token Contract: 'Dev-documentation/Kalp-DLT/KRC-Token-Standard/KRC-721-Token-Contract.md'
              - KRC 1155 Token Contract: 'Dev-documentation/Kalp-DLT/KRC-Token-Standard/KRC-1155-Token-Contract.md'
          - Smart Contract Write,Test, Deploy & Interact:
              - Write the smart contract: 'Dev-documentation/Kalp-DLT/Smart-Contract-Write-Test-Deploy-Interact/Write-the-smart-contract.md'
              - Test the smart contract: 'Dev-documentation/Kalp-DLT/Smart-Contract-Write-Test-Deploy-Interact/Test-the-smart-contract.md'
              - Deploy the smart contract: 'Dev-documentation/Kalp-DLT/Smart-Contract-Write-Test-Deploy-Interact/Deploy-the-smart-contract.md'
              - Interacting with smart contract: 'Dev-documentation/Kalp-DLT/Smart-Contract-Write-Test-Deploy-Interact/Interacting-with-smart-contract.md'
          - Kalp DLT Go Lang Template:
              - Lottery smart contract: 'Dev-documentation/Kalp-DLT/Kalp-DLT-Go-lang-Template/Lottery-smart-contract.md'
              - Soulbound smart contract: 'Dev-documentation/Kalp-DLT/Kalp-DLT-Go-lang-Template/Soulbound-token-smart-contract.md'
              - Splitwise smart contract: 'Dev-documentation/Kalp-DLT/Kalp-DLT-Go-lang-Template/Splitwise-smart-contract.md'
              - Supply chain smart contract: 'Dev-documentation/Kalp-DLT/Kalp-DLT-Go-lang-Template/Supply-chain-smart-contract.md'
          - Kush Library:
              - Kush Library: 'Dev-documentation/Kalp-DLT/Kush-Library/Kush-Library.md'
      - Articles:
              - Smart contract & Go Lang SDK: 'Dev-documentation/Articles/Smart-contract-and-Kalp-Golang-SDK.md'
  - API Reference:
          - Kalp Storage API Documentation: 'API-Reference/Kalp-Storage-API-Documentation.md'
          - Kalp Wallet API Documentation: 'API-Reference/Kalp-Wallet-API-Documentation.md'
          - KS Pay API Documentation: 'API-Reference/KS-Pay-API-Documentation.md'
          - Email Gateway Integration Guide: 'API-Reference/Email-Gateway-Integration-Guide.md'
  - Video Tutorials:
          - Login into Kalp studio: 'Video-Tutorials/Login-into-Kalp-studio.md'
          - Subscribe to Kalp studio products: 'Video-Tutorials/Subscribe-to-Kalp-studio-products.md'
          - Create wallet on Kalp studio: 'Video-Tutorials/Create-wallet-on-Kalp-studio.md'
          - Connect wallet on Kalp studio: 'Video-Tutorials/Connect-wallet-on-Kalp-studio.md'
          - Deploy smart contract on Kalp studio: 'Video-Tutorials/Deploy-a-smart-contract-on-Kalp-studio.md'
          - Generate API endpoints on kalp studio: 'Video-Tutorials/How-to-generate-API-endpoints.md'
          - How to send transaction on kalp studio: 'Video-Tutorials/How-to-send-transactions-on-kalp-studio.md'
  - Release notes:
      - Release version 2.9.0:
          - Release version 2.9.0: 'Release-notes/release-version-2.9.0/release-notes-version-2.9.0.md'
      - Release version 2.8.0:
          - Release version 2.8.0: 'Release-notes/release-version-2.8.0/release-notes-version-2.8.0.md'
      - Release version 2.7.0:
          - Release notes version 2.7.0: 'Release-notes/release-version-2.7.0/release-notes-version-2.7.0.md'
      - Release version 2.6.0:
          - Release notes version 2.6.0: 'Release-notes/release-version-2.6.0/release-notes-version-2.6.0.md'
      - Release version 2.0.0:
          - Release notes version 2.0.0: 'Release-notes/release-version-2.0.0/release-notes-version-2.0.0.md'
      - Release version 1.1.1:
          - Release notes version 1.1.1: 'Release-notes/release-version-1.1.1/release-notes-version-1.1.1.md'
      - Release version 1.1.0:  
          - Release notes version 1.1.0: 'Release-notes/release-version-1.1.0/release-notes-version-1.1.0.md'
      - Release version 1.0.0:
          - Release notes version 1.0.0: 'Release-notes/release-version-1.0.0/release-notes-version-1.0.0.md'
extra:
  social:

    - icon: fontawesome/brands/github
      link: https://github.com/thekalpstudio/
  
    - icon: fontawesome/brands/x-twitter 
      link: https://twitter.com/Kalp_Studio

    - icon: fontawesome/brands/facebook 
      link: https://www.facebook.com/people/Kalp-Studio/61558481045861/

    - icon: fontawesome/brands/instagram 
      link: https://www.instagram.com/kalpstudio.official/

    - icon: fontawesome/brands/linkedin 
      link: https://www.linkedin.com/company/studio-kalp/

    - icon: fontawesome/brands/discord
      link: https://discord.com/invite/JhD7GFVvfv

generator: false`                                                                       